export const CHANGELOG = [
  {
    version: "v1.2.0",
    date: "2025-10-25",
    highlights: ["Improvement & Hotfix!"],
    entries: [
      {
        type: "improvement",
        text: "We have updated the LiveBusView page to be cleaner and more minimised.",
      },
      {
        type: "feature",
        text: "We have added a Submit a Request form for you to submit your suggestions, bug reports and any inquiries."
      }
    ],
  },
  {
    version: "v1.1.0",
    date: "2025-10-24",
    highlights: ["Hotfixes!"],
    entries: [
      {
        type: "feature",
        text: "You can now see the approximate walking time to your stop.",
      },
    ],
  },
  {
    version: "v1.0.0",
    date: "2025-10-23",
    highlights: ["Introducing the My Routes tab!"],
    entries: [
      {
        type: "feature",
        text: "You can now favourite your most frequently visited stops or just your favourite and it will save to your My Routes tab for quicker access. (Plus only)",
      },
      {
        type: "feature",
        text: "Plus users can now set a favourite stop as your home stop or work stop within My Routes with the new Commute feature. You can also enable notifications to notify you when the next bus to [Stop] is under 5 mins away. (Plus only)",
      },
      {
        type: "feature",
        text: "Plus users can now share their commute with other users (both users must have plus). (Plus only)",
      },
      {
        type: "fix",
        text: "Fixed the theme appearance on all pages. (Plus only)",
      },
      {
        type: "improvement",
        text: "Added a rainbow styled background for the LBT Plus page.",
      },
      {
        type: "feature",
        text: "Added a new tab called MyFleetTracker where Plus users can track up to unlimited vehicles in real-time and get notified when they are delayed or go offline. (Plus only)",
      },
      {
        type: "feature",
        text: "Added a Disruption Alerts feature that notifies Plus users of any disruptions in their services in MyFleetTracker. (Plus only)",
      },
      {
        type: "feature",
        text: "Added Crowding estimations for bus services to Live Bus View. Please note that this may not always be available due to Tfl's API. (Plus only)",
      },
      {
        type: "feature",
        text: "Free users can now experience premium access for up to 48 hours using exclusive trial codes — these codes are special and can only be generated by me (the owner 👑). ",
      },
    ],
  },
];
